###############################################################
# This is a reusable workflow. The workflow is callable by 
# by workflows in other repos. This workflow builds an artifact
# of the Databricks content.
###############################################################

name: Callable - Build Databricks Artifact

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      git_checkout_ref: 
        description: 'The branch, tag or SHA to checkout.'
        default: '[MISSING]'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.git_checkout_ref }}
    
    - name: Copy resources
      run: | 
        mv ./Notebooks/ ./artifact
        mv ./Source/Deploy/workspace_cleanup.ps1 ./artifact

    - name: Upload ARM templates as artifact
      uses: actions/upload-artifact@v2
      with:
        name: adb-arm-template
        path: ./artifact
        if-no-files-found: error